import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static AppLocalizations of(BuildContext context) => Localizations.of<AppLocalizations>(context, AppLocalizations)!;

  static const supportedLocales = [Locale('en'), Locale('ar')];

  static const _localizedStrings = {
    'en': {
      'app_title': 'Roamify',
      'home': 'Home',
      'search': 'Search',
      'ai': 'AI',
      'rewards': 'Rewards',
      'settings': 'Settings',
      'login': 'Login',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot password?',
      'welcome': 'Plan your next stay',
      'book_now': 'Book now',
      'favorites': 'Favorites',
      'ai_info': 'AI info coming soon',
      'language': 'Language',
      'theme': 'Dark mode',
      'primary_color': 'Primary color',
      'view': 'View',
      'search_hint': 'Search hotels, cities, or tags',
      'filters_title': 'Filters',
      'max_price': 'Max price',
      'min_rating': 'Min rating',
      'max_distance': 'Max distance (km)',
      'hotel_type': 'Hotel type',
      'reset': 'Reset',
      'apply': 'Apply',
      'filters': 'Filters',
      'sort': 'Sort',
      'results': 'Results',
      'load_more': 'Load more',
      'reduce_motion': 'Reduce motion',
      'recent_searches': 'Recent searches',
      'clear_all': 'Clear all',
      'saved_presets': 'Saved presets',
      'save_preset': 'Save search preset',
      'preset_hint': 'Name this preset (e.g. Family beach)',
      'sort_price': 'Price',
      'sort_rating': 'Rating',
      'sort_distance': 'Distance',
      'popular_stays': 'Popular stays',
      'view_all': 'View all',
      'compare': 'Compare',
      'no_favorites': 'No favorites yet',
      'add_more_hotels': 'Start adding hotels you love',
      'ai_info_title': 'AI insights coming soon',
      'ai_info_desc': 'We will surface smart trip tips about this stay here.',
      'reward_options': 'Reward options',
      'points_balance': 'Points balance',
      'upcoming_trips': 'Upcoming trips',
      'past_trips': 'Past trips',
      'no_upcoming': 'No upcoming trips yet',
      'no_history': 'No history yet',
      'my_bookings': 'My bookings',
      'nights': 'nights',
      'guests': 'guests',
      'check_in': 'Check in',
      'check_out': 'Check out',
      'cancel': 'Cancel',
      'checkedIn': 'Checked in',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'upcoming': 'Upcoming',
      'open_favorites': 'Favorites hub',
      'open_bookings': 'Trips timeline',
      'open_rewards': 'Rewards',
      'view_wallet': 'Rewards wallet',
      'wallet': 'Wallet',
      'redeem': 'Redeem',
      'redeemed': 'Reward redeemed!',
      'insufficient_points': 'Not enough points',
      'refundable': 'Refundable',
      'non_refundable': 'Non-refundable',
      'confirmation_code': 'Confirmation code',
      'perks': 'Perks',
      'timeline': 'Trip timeline',
      'itinerary': 'Itinerary',
      'day_plan_progress': 'Day plan',
      'next_step': 'Next up',
      'no_itinerary': 'No itinerary items yet',
      'trip_preparation': 'Trip preparation',
      'complete_all': 'Complete all',
      'travel_documents': 'Travel documents',
      'docs_progress': 'Document readiness',
      'docs_ready': 'Mark as ready',
      'journal': 'Trip journal',
      'add_entry': 'Add entry',
      'entry_hint': 'Capture a memory, reminder, or tip',
      'journal_empty': 'No journal entries yet',
      'notes': 'Notes',
      'add_note': 'Add a note for the front desk',
      'notes_hint': 'Add arrival time, accessibility needs or pillow preference',
      'save': 'Save',
      'points_earned': 'Points earned',
      'points_earned_desc': 'Complete checkout to unlock points',
      'rewards_wallet_hint': 'Track unlock progress',
    },
    'ar': {
      'app_title': 'روميفاي',
      'home': 'الرئيسية',
      'search': 'بحث',
      'ai': 'الذكاء الاصطناعي',
      'rewards': 'المكافآت',
      'settings': 'الإعدادات',
      'login': 'تسجيل الدخول',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'forgot_password': 'نسيت كلمة المرور؟',
      'welcome': 'خطط لإقامتك القادمة',
      'book_now': 'احجز الآن',
      'favorites': 'المفضلة',
      'ai_info': 'معلومات الذكاء الاصطناعي قريباً',
      'language': 'اللغة',
      'theme': 'الوضع الداكن',
      'primary_color': 'اللون الأساسي',
      'view': 'عرض',
      'search_hint': 'ابحث عن الفنادق أو المدن أو الوسوم',
      'filters_title': 'الفلاتر',
      'max_price': 'أقصى سعر',
      'min_rating': 'أدنى تقييم',
      'max_distance': 'أقصى مسافة (كم)',
      'hotel_type': 'نوع الفندق',
      'reset': 'إعادة تعيين',
      'apply': 'تطبيق',
      'filters': 'الفلاتر',
      'sort': 'فرز',
      'results': 'النتائج',
      'load_more': 'تحميل المزيد',
      'reduce_motion': 'تقليل الحركة',
      'recent_searches': 'عمليات البحث الأخيرة',
      'clear_all': 'مسح الكل',
      'saved_presets': 'عمليات البحث المحفوظة',
      'save_preset': 'حفظ البحث',
      'preset_hint': 'اسم للبحث المحفوظ',
      'sort_price': 'السعر',
      'sort_rating': 'التقييم',
      'sort_distance': 'المسافة',
      'popular_stays': 'إقامات رائجة',
      'view_all': 'عرض الكل',
      'compare': 'مقارنة',
      'no_favorites': 'لا توجد مفضلة بعد',
      'add_more_hotels': 'ابدأ بإضافة الفنادق التي تعجبك',
      'ai_info_title': 'رؤى الذكاء الاصطناعي قريباً',
      'ai_info_desc': 'سنظهر نصائح سفر ذكية عن هذا الفندق هنا.',
      'reward_options': 'خيارات المكافآت',
      'points_balance': 'رصيد النقاط',
      'upcoming_trips': 'رحلات قادمة',
      'past_trips': 'رحلات سابقة',
      'no_upcoming': 'لا توجد رحلات قادمة',
      'no_history': 'لا يوجد سجل بعد',
      'my_bookings': 'حجوزاتي',
      'nights': 'ليالٍ',
      'guests': 'ضيوف',
      'check_in': 'تسجيل الدخول',
      'check_out': 'تسجيل الخروج',
      'cancel': 'إلغاء',
      'checkedIn': 'تم تسجيل الدخول',
      'completed': 'مكتمل',
      'cancelled': 'ملغى',
      'upcoming': 'قادمة',
      'open_favorites': 'مركز المفضلة',
      'open_bookings': 'خط رحلاتك',
      'open_rewards': 'المكافآت',
      'view_wallet': 'محفظة النقاط',
      'wallet': 'المحفظة',
      'redeem': 'استبدال',
      'redeemed': 'تم استبدال المكافأة!',
      'insufficient_points': 'الرصيد غير كافٍ',
      'refundable': 'قابل للاسترداد',
      'non_refundable': 'غير قابل للاسترداد',
      'confirmation_code': 'رقم التأكيد',
      'perks': 'مزايا',
      'timeline': 'مخطط الرحلة',
      'itinerary': 'جدول الأنشطة',
      'day_plan_progress': 'خطة اليوم',
      'next_step': 'التالي',
      'no_itinerary': 'لا يوجد جدول أنشطة بعد',
      'trip_preparation': 'التحضير للرحلة',
      'complete_all': 'إنهاء الكل',
      'travel_documents': 'وثائق السفر',
      'docs_progress': 'جاهزية الوثائق',
      'docs_ready': 'وضعها جاهزة',
      'journal': 'مذكرات الرحلة',
      'add_entry': 'إضافة ملاحظة',
      'entry_hint': 'دوّن ذكرى أو تذكيراً أو نصيحة',
      'journal_empty': 'لا توجد مذكرات بعد',
      'notes': 'ملاحظات',
      'add_note': 'أضف ملاحظة للاستقبال',
      'notes_hint': 'أضف وقت الوصول أو الاحتياجات الخاصة أو نوع الوسادة',
      'save': 'حفظ',
      'points_earned': 'النقاط المكتسبة',
      'points_earned_desc': 'أكمل إنهاء السكن للحصول على النقاط',
      'rewards_wallet_hint': 'تابع تقدمك',
    },
  };

  String translate(String key) => _localizedStrings[locale.languageCode]?[key] ?? key;
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate old) => false;
}
